apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-test
  namespace: %USER%-argocd
spec:
  destination:
    namespace: %USER%-dev
    server: https://kubernetes.default.svc
  source:
    path: content/modules/ROOT/examples/health/bgd/base
    repoURL: https://github.com/OpenShiftDemos/advanced-gitops-workshop/
    targetRevision: HEAD
  project: workshop
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
