  resource.customizations.health._.PersistentVolumeClaim: |
      hs = {}
      if (obj.status ~= nil and obj.status.phase ~= nil) then
          if obj.status.phase == "Pending" or obj.status.phase == "Bound" then <1>
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
          elseif obj.status.phase == "Lost" then <2>
              hs.status = "Degraded"
              hs.message = obj.status.phase
              return hs
          end
      end
      hs.status = "Unknown" <3>
      hs.message = "Waiting for PVC status"
      return hs
