apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workshop
  namespace: user%USERNUM%-argocd
spec:
  description: Team%USERNUM%'s' Project
  destinations:
  - namespace: user%USERNUM%-dev
    server: https://kubernetes.default.svc
  - namespace: user%USERNUM%-stage
    server: https://kubernetes.default.svc
  - namespace: user%USERNUM%-prod
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/OpenShiftDemos/advanced-gitops-workshop
  roles:
    - description: Team%USERNUM% Admins
      name: admin
      groups:
        - team%USERNUM%
      policies:
        - p, proj:workshop:admin, applications, *, workshop/*, allow
        - p, proj:workshop:admin, exec, create, workshop/*, allow
