= GitOps Configuration
include::_attributes.adoc[]

== Argo CD CLI

We wil use the ArgoCD CLI to explore your GitOps environment in more detail. A secret has been pre-created in the `{user}-argocd`
namespace called `argocd-cli` that provides the credentials needed to login into Argo CD.

[NOTE]
Normally when using Argo CD with OIDC the login would be done with using the `--sso` switch
which starts up a local web server to handle the OIDC callback on localhost. However since
our terminal is running in a pod in OpenShift this is not possible. Therefore a local account, `{user}-cli`, has been pre-created
with identical permissions to the SSO user. Normally local accounts in Argo CD should only
be used for automation not for users.

To provision secret into the terminal as exported environment variables run the following
commands:

[.console-input]
[source,sh,subs="attributes",role=execute]
----
export ARGOCD_AUTH_TOKEN=$(oc get secret argocd-cli -n {user}-argocd -o jsonpath="{.data.ARGOCD_AUTH_TOKEN}" | base64 -d)
export ARGOCD_SERVER=$(oc get secret argocd-cli -n {user}-argocd -o jsonpath="{.data.ARGOCD_SERVER}" | base64 -d)
export ARGOCD_USERNAME=$(oc get secret argocd-cli -n {user}-argocd -o jsonpath="{.data.ARGOCD_USERNAME}" | base64 -d)
alias argocd='f(){ argocd "$@" --grpc-web;  unset -f f; }; f'
----

The Argo CD CLI will use the specified environment variables automatically and not require an explicit login. Additionally
the alias command at the end will ensure that when the `argocd` is called the parameter `--grpc-web` is automatically added. Since
we are routing commands through the OpenShift Route this parameter is needed to avoid superfluous warnings.

[IMPORTANT]
If you restart the terminal interface you may need to run the above commands again in order to access Argo CD
from the command line.

Test the variables are set by using the Argo CD CLI to view the Applications that were shown in the user interface:

[.console-input]
[source,sh,subs="attributes",role=execute]
----
argocd app list
----

The following output will be provided showing the application name, the sync and health status, the source and destination.

[.console-output]
[source,bash,subs="attributes+,+macros"]
----
NAME                    CLUSTER     NAMESPACE   PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                                        PATH                              TARGET
{user}-argocd/dev-tools  in-cluster  {user}-cicd  {user}    Synced  Healthy  Auto        <none>      https://github.com/AdvancedDevSecOpsWorkshop/bootstrap.git  infra/dev-tools/overlays/default  HEAD
----

A detailed view of the Application can be retrieved by using the `get` command:

[.console-input]
[source,sh,subs="attributes",role=execute]
----
argocd app get {user}-argocd/dev-tools
----

Various details of the Application are shown including a list of resources that the application is managing and their associated statuses.

[.console-output]
[source,bash,subs="attributes+,+macros"]
----
Name:               {user}-argocd/dev-tools
Project:            {user}
Server:             in-cluster
Namespace:          {user}-cicd
URL:                https://argocd-server-gitops.apps.cluster-wvcx7.sandbox1429.opentlc.com/applications/dev-tools
Source:
- Repo:             https://github.com/AdvancedDevSecOpsWorkshop/bootstrap.git
  Target:           HEAD
  Path:             infra/dev-tools/overlays/default
SyncWindow:         Sync Allowed
Sync Policy:        Automated
Sync Status:        Synced to HEAD (482bc44)
Health Status:      Healthy

GROUP               KIND                   NAMESPACE    NAME                       STATUS  HEALTH   HOOK  MESSAGE
                    Secret                 {user}-cicd   sonarqube-admin            Synced                 secret/sonarqube-admin created
                    PersistentVolumeClaim  {user}-cicd   nexus                      Synced  Healthy        persistentvolumeclaim/nexus created
                    PersistentVolumeClaim  {user}-cicd   sonarqube-data             Synced  Healthy        persistentvolumeclaim/sonarqube-data created
                    PersistentVolumeClaim  {user}-cicd   postgresql-sonarqube-data  Synced  Healthy        persistentvolumeclaim/postgresql-sonarqube-data created
                    Service                {user}-cicd   sonarqube                  Synced  Healthy        service/sonarqube created
                    Service                {user}-cicd   nexus                      Synced  Healthy        service/nexus created
                    Service                {user}-cicd   postgresql-sonarqube       Synced  Healthy        service/postgresql-sonarqube created
apps                Deployment             {user}-cicd   nexus                      Synced  Healthy        deployment.apps/nexus created
apps                Deployment             {user}-cicd   sonarqube                  Synced  Healthy        deployment.apps/sonarqube created
batch               Job                    {user}-cicd   configure-nexus            Synced  Healthy        job.batch/configure-nexus created
batch               Job                    {user}-cicd   configure-sonarqube        Synced  Healthy        job.batch/configure-sonarqube created
route.openshift.io  Route                  {user}-cicd   nexus                      Synced  Healthy        route.route.openshift.io/nexus created
apps.openshift.io   DeploymentConfig       {user}-cicd   postgresql-sonarqube       Synced  Healthy        deploymentconfig.apps.openshift.io/postgresql-sonarqube created
route.openshift.io  Route                  {user}-cicd   sonarqube                  Synced  Healthy        route.route.openshift.io/sonarqube created
----

In addition to retrieving information about the Application, various tasks can be performed via the CLI including syncing, refreshing and modifying the Application. We
will look at these in more depth in subsequent sections.
