kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
